'''
You are given two strings, s and t which only consist of lowercase letters.
t is generated by shuffling the letters in s as well as potentially adding an additional random character.
Return the letter that was randomly added to t if it exists, otherwise, return ’  ‘.
Note: You may assume that at most one additional character can be added to t.
'''


def solve(s: str, t: str) -> str:
    freq = {}
    for char in s:
        if char in freq:
            freq[char] += 1
        else:
            freq[char] = 1
    seen = ''
    for char in t:
        if char in freq:
            freq[char] -= 1
        elif char not in freq:
            seen += char
    return seen


def main():
    assert solve(s = "foobar", t = "barfoot") == 't'
    assert solve(s = "ide", t = "idea") == 'a'
    assert solve(s = "coding", t="ingcod") == ''


if __name__ == '__main__':
    main()
